task:
  name: bash script.sh
  container:
    image: crazyuploader/minimal_ubuntu:latest
    cpu: 8
    memory: 8G
  environment:
    GITLAB_TOKEN: ENCRYPTED[94da4b52fd206ca1f4a5a45e6458558c1702e96d40c538178cb2e6088b68f87f143d92798971cd786397f97049ecd1a8]
  script_script: bash script.sh
