dist: bionic
language: bash
script:
  - wget -nv https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r377782.tar.gz
  - tar -xf clang-r377782.tar.gz
  - rm clang-r377782.tar.gz
  - ls
